# Generated by Django 4.1.7 on 2023-05-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vrticconnect", "0002_alter_user_grupa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="Email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Ime",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Prezime",
        ),
        migrations.RemoveField(
            model_name="user",
            name="Username",
        ),
    ]
