# Generated by Django 4.1.7 on 2023-05-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vrticconnect", "0003_remove_user_email_remove_user_ime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Objava",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Naslov", models.CharField(max_length=200)),
                ("Tekst", models.TextField(max_length=1000)),
                ("Datum_objave", models.DateTimeField(verbose_name="date published")),
                (
                    "Autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
