# Generated by Django 4.1.7 on 2023-05-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vrticconnect", "0004_objava"),
    ]

    operations = [
        migrations.AddField(
            model_name="objava",
            name="Grupa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vrticconnect.grupa",
            ),
        ),
    ]
