# Generated by Django 4.1.7 on 2023-05-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vrticconnect", "0006_poruka"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Mail_kontakt",
            field=models.BooleanField(default=False),
        ),
    ]
