# Generated by Django 4.1.7 on 2023-05-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vrticconnect", "0007_user_mail_kontakt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aktivnost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Naziv", models.CharField(max_length=200)),
                ("Datum_aktivnosti", models.DateField()),
                (
                    "Grupa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vrticconnect.grupa",
                    ),
                ),
            ],
        ),
    ]
