# Generated by Django 4.1.7 on 2023-08-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vrticconnect", "0008_aktivnost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fotografija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Naslov", models.CharField(max_length=100)),
                ("Fotografija", models.ImageField(upload_to="fotografije/")),
                ("Datum_spremanja", models.DateTimeField(auto_now_add=True)),
                (
                    "Grupa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vrticconnect.grupa",
                    ),
                ),
            ],
        ),
    ]
